apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: nginx
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: bitnami/nginx:1.21.3
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            limits:
              cpu: 0.5
              memory: 512Mi
            requests:
              cpu: 0.2
              memory: 256Mi
          imagePullPolicy: Always
