name: Conftest Tests

on:
  push:
    branches:
      - main  # Adjust this branch name if necessary

jobs:
  test:
    name: Test YAML files
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Show Working Directory
        run: |
          pwd

      - name: Run Conftest
        run: |
          for file in $(find /conftest-demo -name '*.yml'); do
            conftest test $file  # Use 'conftest' directly since it's available on the self-hosted runner
          done
