name: Conftest Tests

on:
  push:
    branches:
      - main  # Adjust this branch name if necessary

jobs:
  test:
    name: Test YAML file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          sudo snap install kubectl --classic

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <your-aws-region>  # Replace with your AWS region

      - name: Install conftest
        run: |
          wget -O conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.42.1/conftest_0.42.1_Linux_x86_64.tar.gz
          tar -xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run Conftest
        run: |
          if conftest test nginxpass.yml; then
            echo "Conftest passed for nginxpass.yml"
          else
            echo "Conftest failed for nginxpass.yml"
            exit 1
          fi
