name: Conftest Tests

on:
  push:
    branches:
      - main  # Adjust this branch name if necessary

jobs:
  test:
    name: Test YAML file
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Find YAML files
        id: find-files
        run: |
          echo "::set-output name=files::$(find -name '*.yml')"
          
      - name: Print YAML file paths
        run: |
          echo "${{ steps.find-files.outputs.files }}"
          
      - name: Run Conftest and Deploy
        run: |
          cd /home/nitesh/Documents
          for file in $(find -name '*.yml'); do
            if conftest test "$file"; then
              kubectl apply -f "$file"
            else
              echo "Skipping deployment of $file as it failed Conftest tests"
            fi
            done
          
        

