name: Conftest Tests

on:
  push:
    branches:
      - dev  # Adjust this branch name if necessary

jobs:
  test:
    name: Test YAML file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          sudo snap install kubectl --classic

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA2CUJN4MFHWE4RW6Z
          aws-secret-access-key: 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
          aws-region: ca-central-1  

      - name: Install conftest
        run: |
          wget -O conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.42.1/conftest_0.42.1_Linux_x86_64.tar.gz
          tar -xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/
          
      - name: Update kubeconfig
        run: |
          aws eks --region ca-central-1 update-kubeconfig --name conftest

      - name: Run Conftest
        run: |
          if conftest test nginx-fail; then
            kubectl apply -f nginx-fail.yml
          else
            echo "Conftest failed for nginx-fail.yml"
            exit 1
          fi
