name: Conftest Tests

on:
  push:
    branches:
      - main  # Adjust this branch name if necessary

jobs:
  test:
    name: Test YAML files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install conftest
        uses: open-policy-agent/conftest-action@v1

      - name: Run Conftest and Deploy
        run: |
          conftest test nginx.yml
