name: Conftest Tests

on:
  push:
    branches:
      - main  # Adjust this branch name if necessary

jobs:
  test:
    name: Test YAML files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install conftest
        run: |
          wget -O conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.42.1/conftest_0.42.1_Linux_x86_64.tar.gz
          tar -xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run Conftest and Deploy
        run: |
          for file in $(find -name '*.yml'); do
            if conftest test "$file"; then
              kubectl apply -f "$file"
            else
              echo "Skipping deployment of $file as it failed Conftest tests"
            fi
          done
